spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/store_api?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:MyPassword!}
  docker:
    compose:
      lifecycle-management: start-only
  jpa:
    show-sql: true
websiteUrl: ${WEBSITE_URL:http://localhost:8080}
admin:
  default-email: ${DEFAULT_ADMIN_EMAIL:admin@tyronegrocery.local}
  default-password: ${DEFAULT_ADMIN_PASSWORD:Admin@12345}
